/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.session_3;

import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author USER
 */
public class NetPayGui extends javax.swing.JFrame {

     Connection conn = null;
     ResultSet rs = null;
     PreparedStatement pst = null;

     // Creating the NetPayClass.java Object
     NetPayClass npc;

     private void Update_table() {
          try {
	    String sql = "select * from emptable";
	    pst = conn.prepareStatement(sql);
	    rs = pst.executeQuery();
	    emptTableJT.setModel(DbUtils.resultSetToTableModel(rs));
          } catch (Exception e) {
	    JOptionPane.showMessageDialog(null, e);
          } finally {

	    try {
	         rs.close();
	         pst.close();

	    } catch (Exception e) {

	    }

          }
     }

     // Checking Input Fields
     public boolean checkInputs() {
          if (empIDTF.getText().trim() == null || empNameTF.getText().trim() == null || hoursWorkedTF.getText().trim() == null || hourlyPayRateTF.getText().trim() == null || fedTaxRateTF.getText().trim() == null || stateTaxRateTF.getText().trim() == null) {
	    return false;
          } else {
	    try {
	         empIDTF.getText().trim();
	         return true;
	    } catch (NumberFormatException e) {
	         return false;
//                JOptionPane.showMessageDialog(null, e);
	    }
          }
     }

     /**
      * Creates new form NetPayGui
      */
     public NetPayGui() {
          initComponents();
          conn = DBConnect.java_db();
          Update_table();
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING:
      * Do NOT modify this code. The content of this method is always regenerated by the
      * Form Editor.
      */
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchTF = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        empIDTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        empNameTF = new javax.swing.JTextField();
        hoursWorkedTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fedTaxRateTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        stateTaxRateTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        computeBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        hourlyPayRateTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        grossPayLB = new javax.swing.JLabel();
        fedTaxAmountLB = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        stateTaxAmountLB = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        totalDeductionLB = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        netPayLB = new javax.swing.JLabel();
        updateBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        insertBTN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emptTableJT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Netpay App");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search record");

        searchTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTFKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Employee Inputs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        empIDTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Employee ID");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Employee's name");

        empNameTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        hoursWorkedTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Hours worked");

        fedTaxRateTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Federal Tax Rate");

        stateTaxRateTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("State Tax Rate");

        computeBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        computeBTN.setText("Compute");
        computeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeBTNActionPerformed(evt);
            }
        });

        resetBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });

        exitBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Hourly pay rate");

        hourlyPayRateTF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(computeBTN)
                .addGap(39, 39, 39)
                .addComponent(resetBTN)
                .addGap(42, 42, 42)
                .addComponent(exitBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(empIDTF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(empNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(hoursWorkedTF, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(fedTaxRateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(stateTaxRateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(hourlyPayRateTF, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursWorkedTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hourlyPayRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fedTaxRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateTaxRateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(computeBTN)
                    .addComponent(resetBTN)
                    .addComponent(exitBTN))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Output", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Grosspay");

        grossPayLB.setBackground(new java.awt.Color(255, 255, 255));
        grossPayLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        grossPayLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        grossPayLB.setOpaque(true);

        fedTaxAmountLB.setBackground(new java.awt.Color(255, 255, 255));
        fedTaxAmountLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fedTaxAmountLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fedTaxAmountLB.setOpaque(true);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Federal Tax Amount");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("State Tax Amount");

        stateTaxAmountLB.setBackground(new java.awt.Color(255, 255, 255));
        stateTaxAmountLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        stateTaxAmountLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stateTaxAmountLB.setOpaque(true);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Total Deduction");

        totalDeductionLB.setBackground(new java.awt.Color(255, 255, 255));
        totalDeductionLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalDeductionLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalDeductionLB.setOpaque(true);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Net pay");

        netPayLB.setBackground(new java.awt.Color(255, 255, 255));
        netPayLB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        netPayLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        netPayLB.setOpaque(true);

        updateBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });

        insertBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        insertBTN.setText("Insert");
        insertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(netPayLB, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalDeductionLB, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stateTaxAmountLB, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grossPayLB, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(fedTaxAmountLB, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertBTN)
                .addGap(39, 39, 39)
                .addComponent(updateBTN)
                .addGap(42, 42, 42)
                .addComponent(deleteBTN)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(grossPayLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fedTaxAmountLB, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(stateTaxAmountLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(totalDeductionLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(netPayLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertBTN)
                    .addComponent(updateBTN)
                    .addComponent(deleteBTN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "Employee Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jPanel3.setAutoscrolls(true);

        emptTableJT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emptTableJT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        emptTableJT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emptTableJTMouseClicked(evt);
            }
        });
        emptTableJT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emptTableJTKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(emptTableJT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(519, 519, 519)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44)
                                .addComponent(searchTF))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBTNActionPerformed
         // TODO add your handling code here:
//        if (checkInputs()) {
         try {
	   String sql = "insert into emptable(EmpID, Name, HoursWorked, HourlyRate, FederalTaxRate, StateTaxRate, GrossPay, FederalTaxAmount, StateTaxAmount, TotalDeduction, NetPay) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	   pst = conn.prepareStatement(sql);

	   pst.setString(1, empIDTF.getText().trim());
	   pst.setString(2, empNameTF.getText().trim());
	   pst.setString(3, hoursWorkedTF.getText().trim());
	   pst.setString(4, hourlyPayRateTF.getText().trim());
	   pst.setString(5, fedTaxRateTF.getText().trim());
	   pst.setString(6, stateTaxRateTF.getText().trim());
	   pst.setString(7, grossPayLB.getText().trim());
	   pst.setString(8, fedTaxAmountLB.getText().trim());
	   pst.setString(9, stateTaxAmountLB.getText().trim());
	   pst.setString(10, totalDeductionLB.getText().trim());
	   pst.setString(11, netPayLB.getText().trim());

	   pst.executeUpdate();
	   JOptionPane.showMessageDialog(null, "Record Inserted Successfully.");

	   // Reloads the frame to refresh
	   // Closes the frame
	   this.dispose();

	   // Reopens the Frame
	   NetPayGui.main(new String[]{});

         } catch (HeadlessException | SQLException e) {
	   JOptionPane.showMessageDialog(null, "No Primary key or Record Already Exists");
         }

//        } 
//        else {
//            JOptionPane.showMessageDialog(null, "One or More Field Are Empty");
//        }
         Update_table();
    }//GEN-LAST:event_insertBTNActionPerformed

    private void computeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeBTNActionPerformed
         // TODO add your handling code here:

         try {
	   double hoursWorked = Double.parseDouble(hoursWorkedTF.getText().trim());
	   double hourlyPayRate = Double.parseDouble(hourlyPayRateTF.getText().trim());
	   double fedTaxRate = Double.parseDouble(fedTaxRateTF.getText().trim());
	   double stateTaxRate = Double.parseDouble(stateTaxRateTF.getText().trim());

	   npc = new NetPayClass(hoursWorked, hourlyPayRate, fedTaxRate, stateTaxRate);

	   double grossPay = npc.grossPay();
	   double fedTaxAmount = npc.fedTaxWithHolding();
	   double stateTaxAmount = npc.stateTaxWithHolding();
	   double totalDeduction = npc.totalDeduction();
	   double netPay = npc.netPayAmount();

	   grossPayLB.setText(String.format("%.2f", grossPay));
	   fedTaxAmountLB.setText(String.format("%.2f", fedTaxAmount));
	   stateTaxAmountLB.setText(String.format("%.2f", stateTaxAmount));
	   totalDeductionLB.setText(String.format("%.2f", totalDeduction));
	   netPayLB.setText(String.format("%.2f", fedTaxAmount));

         } catch (Exception e) {
	   JOptionPane.showMessageDialog(null, "INVALID VALUE");
         }

         // INSTANTIATING THE CONSTRUCTOR
    }//GEN-LAST:event_computeBTNActionPerformed

    private void emptTableJTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emptTableJTKeyReleased
         // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_UP) {
	   int row = emptTableJT.getSelectedRow();
	   String Table_click = (emptTableJT.getModel().getValueAt(row, 0).toString());

	   try {
	        String sql = "select * from emptable where EmpID='" + Table_click + "' ";
	        pst = conn.prepareStatement(sql);
	        rs = pst.executeQuery();

	        if (rs.next()) {
		  String add1 = rs.getString("EmpID");
		  empIDTF.setText(add1);

		  String add2 = rs.getString("Name");
		  empNameTF.setText(add2);

		  String add3 = rs.getString("HoursWorked");
		  hoursWorkedTF.setText(add3);

		  String add4 = rs.getString("HourlyRate");
		  hourlyPayRateTF.setText(add4);

		  String add5 = rs.getString("FederalTaxRate");
		  fedTaxRateTF.setText(add5);

		  String add6 = rs.getString("StateTaxRate");
		  stateTaxRateTF.setText(add6);

		  String add7 = rs.getString("GrossPay");
		  grossPayLB.setText(add7);

		  String add8 = rs.getString("FederalTaxAmount");
		  fedTaxAmountLB.setText(add8);

		  String add9 = rs.getString("StateTaxAmount");
		  stateTaxAmountLB.setText(add9);

		  String add10 = rs.getString("TotalDeduction");
		  totalDeductionLB.setText(add10);

		  String add11 = rs.getString("NetPay");
		  netPayLB.setText(add11);

	        }

	   } catch (SQLException e) {
	        JOptionPane.showMessageDialog(null, e);
	   }
         }

    }//GEN-LAST:event_emptTableJTKeyReleased

    private void emptTableJTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emptTableJTMouseClicked

         int row = emptTableJT.getSelectedRow();
         String Table_click = (emptTableJT.getModel().getValueAt(row, 0).toString());

         try {
	   String sql = "select * from emptable where EmpID='" + Table_click + "' ";
	   pst = conn.prepareStatement(sql);
	   rs = pst.executeQuery();

	   if (rs.next()) {
	        String add1 = rs.getString("EmpID");
	        empIDTF.setText(add1);

	        String add2 = rs.getString("Name");
	        empNameTF.setText(add2);

	        String add3 = rs.getString("HoursWorked");
	        hoursWorkedTF.setText(add3);

	        String add4 = rs.getString("HourlyRate");
	        hourlyPayRateTF.setText(add4);

	        String add5 = rs.getString("FederalTaxRate");
	        fedTaxRateTF.setText(add5);

	        String add6 = rs.getString("StateTaxRate");
	        stateTaxRateTF.setText(add6);

	        String add7 = rs.getString("GrossPay");
	        grossPayLB.setText(add7);

	        String add8 = rs.getString("FederalTaxAmount");
	        fedTaxAmountLB.setText(add8);

	        String add9 = rs.getString("StateTaxAmount");
	        stateTaxAmountLB.setText(add9);

	        String add10 = rs.getString("TotalDeduction");
	        totalDeductionLB.setText(add10);

	        String add11 = rs.getString("NetPay");
	        netPayLB.setText(add11);

	   }

         } catch (SQLException e) {
	   JOptionPane.showMessageDialog(null, e);
         }


    }//GEN-LAST:event_emptTableJTMouseClicked

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
         try {
	   String Query = "UPDATE emptable SET Name = ?, HoursWorked = ?, HourlyRate = ?, FederalTaxRate = ?, StateTaxRate = ?, GrossPay = ?, FederalTaxAmount = ?, StateTaxAmount = ?, TotalDeduction = ?, NetPay = ?  WHERE EmpID = ?";
	   pst = conn.prepareStatement(Query);

	   pst.setString(1, empNameTF.getText().trim());
	   pst.setString(2, hoursWorkedTF.getText().trim());
	   pst.setString(3, hourlyPayRateTF.getText().trim());
	   pst.setString(4, fedTaxRateTF.getText().trim());
	   pst.setString(5, stateTaxRateTF.getText().trim());
	   pst.setString(6, grossPayLB.getText().trim());
	   pst.setString(7, fedTaxAmountLB.getText().trim());
	   pst.setString(8, stateTaxAmountLB.getText().trim());
	   pst.setString(9, totalDeductionLB.getText().trim());
	   pst.setString(10, netPayLB.getText().trim());
	   pst.setString(11, empIDTF.getText().trim());

	   pst.executeUpdate();
	   JOptionPane.showMessageDialog(null, "Record Updated");

         } catch (SQLException e) {
	   Logger.getLogger(NetPayGui.class.getName()).log(Level.SEVERE, null, e);
         }

         Update_table();
    }//GEN-LAST:event_updateBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
         int promptYesNo = JOptionPane.showConfirmDialog(null, "Message: Do you really want to delete", "Title: Delete", JOptionPane.YES_NO_OPTION);

         if (promptYesNo == 0) {
	   try {
	        String sql = "delete from emptable where EmpID=?";
	        pst = conn.prepareStatement(sql);

	        pst.setString(1, empIDTF.getText().trim());

	        pst.execute();
	        JOptionPane.showMessageDialog(null, "Deleted");

	   } catch (HeadlessException | SQLException e) {
	        JOptionPane.showMessageDialog(null, e);
	   }
         }
         Update_table();
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void searchTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTFKeyReleased
         try {
	   String sql = "select * from emptable where EmpID = ?";

	   pst = conn.prepareStatement(sql);
	   pst.setString(1, searchTF.getText());
	   rs = pst.executeQuery();

	   String add1 = rs.getString("EmpID");
	   empIDTF.setText(add1);

	   String add2 = rs.getString("Name");
	   empNameTF.setText(add2);

	   String add3 = rs.getString("HoursWorked");
	   hoursWorkedTF.setText(add3);

	   String add4 = rs.getString("HourlyRate");
	   hourlyPayRateTF.setText(add4);

	   String add5 = rs.getString("FederalTaxRate");
	   fedTaxRateTF.setText(add5);

	   String add6 = rs.getString("StateTaxRate");
	   stateTaxRateTF.setText(add6);

	   String add7 = rs.getString("GrossPay");
	   grossPayLB.setText(add7);

	   String add8 = rs.getString("FederalTaxAmount");
	   fedTaxAmountLB.setText(add8);

	   String add9 = rs.getString("StateTaxAmount");
	   stateTaxAmountLB.setText(add9);

	   String add10 = rs.getString("TotalDeduction");
	   totalDeductionLB.setText(add10);

	   String add11 = rs.getString("NetPay");
	   netPayLB.setText(add11);

         } catch (SQLException e) {

         } finally {
	   try {
	        rs.close();
	        pst.close();
	   } catch (Exception e) {
	   }
         }
    }//GEN-LAST:event_searchTFKeyReleased

    private void searchTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTFKeyPressed
         // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
	   try {
	        String sql = "select * from emptable where EmpID = ?";

	        pst = conn.prepareStatement(sql);
	        pst.setString(1, searchTF.getText());
	        rs = pst.executeQuery();

	        String add1 = rs.getString("EmpID");
	        empIDTF.setText(add1);

	        String add2 = rs.getString("Name");
	        empNameTF.setText(add2);

	        String add3 = rs.getString("HoursWorked");
	        hoursWorkedTF.setText(add3);

	        String add4 = rs.getString("HourlyRate");
	        hourlyPayRateTF.setText(add4);

	        String add5 = rs.getString("FederalTaxRate");
	        fedTaxRateTF.setText(add5);

	        String add6 = rs.getString("StateTaxRate");
	        stateTaxRateTF.setText(add6);

	        String add7 = rs.getString("GrossPay");
	        grossPayLB.setText(add7);

	        String add8 = rs.getString("FederalTaxAmount");
	        fedTaxAmountLB.setText(add8);

	        String add9 = rs.getString("StateTaxAmount");
	        stateTaxAmountLB.setText(add9);

	        String add10 = rs.getString("TotalDeduction");
	        totalDeductionLB.setText(add10);

	        String add11 = rs.getString("NetPay");
	        netPayLB.setText(add11);

	   } catch (SQLException e) {

	   } finally {
	        try {
		  rs.close();
		  pst.close();
	        } catch (Exception e) {
	        }
	   }
         }
    }//GEN-LAST:event_searchTFKeyPressed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetBTNActionPerformed

     private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
          // TODO add your handling code here:
     }//GEN-LAST:event_exitBTNActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
          /* Set the Nimbus look and feel */
          //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
          /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
           */
          try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	         if ("Nimbus".equals(info.getName())) {
		   javax.swing.UIManager.setLookAndFeel(info.getClassName());
		   break;
	         }
	    }
          } catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(NetPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(NetPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(NetPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(NetPayGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
          //</editor-fold>

          /* Create and display the form */
          java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
	         new NetPayGui().setVisible(true);
	    }
          });
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton computeBTN;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JTextField empIDTF;
    private javax.swing.JTextField empNameTF;
    private javax.swing.JTable emptTableJT;
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel fedTaxAmountLB;
    private javax.swing.JTextField fedTaxRateTF;
    private javax.swing.JLabel grossPayLB;
    private javax.swing.JTextField hourlyPayRateTF;
    private javax.swing.JTextField hoursWorkedTF;
    private javax.swing.JButton insertBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel netPayLB;
    private javax.swing.JButton resetBTN;
    private javax.swing.JTextField searchTF;
    private javax.swing.JLabel stateTaxAmountLB;
    private javax.swing.JTextField stateTaxRateTF;
    private javax.swing.JLabel totalDeductionLB;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables
}
